version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: flaskdb
      MYSQL_USER: flaskuser
      MYSQL_PASSWORD: flaskpassword
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10

  web:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_NAME: flaskdb
      DB_USER: flaskuser
      DB_PASSWORD: flaskpassword
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app

volumes:
  mysql_data:
